{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "7ZnGv3SzFchZ"
   },
   "outputs": [],
   "source": [
    "!pip install transformers==4.21.2\n",
    "!pip install sentencepiece\n",
    "!pip install torch_optimizer\n",
    "!pip install pytorch-lightning\n",
    "!pip install datasets\n",
    "!pip install evaluate\n",
    "!pip install wandb\n",
    "\n",
    "!wandb login df8cdd3f4ff34f32668158f84ae4a1ede7570a92"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true,
    "id": "7Nyxy0PGFihc",
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/root/anaconda3/envs/bkt/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.996-ko-0.9.2 is an invalid version and will not be supported in a future release\n",
      "  warnings.warn(\n",
      "|train| = 60 |valid| = 1\n",
      "#total_iters = 35 #warmup_iters = 0\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Currently logged in as: \u001b[33mhurontrara\u001b[0m. Use \u001b[1m`wandb login --relogin`\u001b[0m to force relogin\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: wandb version 0.13.9 is available!  To upgrade, please run:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:  $ pip install wandb --upgrade\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Tracking run with wandb version 0.13.8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Run data is saved locally in \u001b[35m\u001b[1m./wandb/run-20230117_130545-lz1zeehh\u001b[0m\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Run \u001b[1m`wandb offline`\u001b[0m to turn off syncing.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Syncing run \u001b[33mskt_lr_2e_5_epochs_5_length_512(0fold)\u001b[0m\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: ‚≠êÔ∏è View project at \u001b[34m\u001b[4mhttps://wandb.ai/hurontrara/AIxBookathon\u001b[0m\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: üöÄ View run at \u001b[34m\u001b[4mhttps://wandb.ai/hurontrara/AIxBookathon/runs/lz1zeehh\u001b[0m\n",
      "/root/anaconda3/envs/bkt/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:441: LightningDeprecationWarning: Setting `Trainer(gpus=1)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=1)` instead.\n",
      "  rank_zero_deprecation(\n",
      "GPU available: True (cuda), used: True\n",
      "/root/anaconda3/envs/bkt/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.996-ko-0.9.2 is an invalid version and will not be supported in a future release\n",
      "  warnings.warn(\n",
      "TPU available: False, using: 0 TPU cores\n",
      "IPU available: False, using: 0 IPUs\n",
      "HPU available: False, using: 0 HPUs\n",
      "LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]\n",
      "/root/anaconda3/envs/bkt/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py:329: RuntimeWarning: The lr scheduler dict contains the key(s) ['interval'], but the keys will be ignored. You need to call `lr_scheduler.step()` manually in manual optimization.\n",
      "  rank_zero_warn(\n",
      "\n",
      "  | Name  | Type            | Params\n",
      "------------------------------------------\n",
      "0 | model | GPT2LMHeadModel | 1.2 B \n",
      "------------------------------------------\n",
      "629 M     Trainable params\n",
      "533 M     Non-trainable params\n",
      "1.2 B     Total params\n",
      "4,650.225 Total estimated model params size (MB)\n",
      "Sanity Checking: 0it [00:00, ?it/s]/root/anaconda3/envs/bkt/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.\n",
      "  rank_zero_warn(\n",
      "Sanity Checking DataLoader 0: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 1/1 [00:00<00:00,  1.32it/s]valid_loss : 3.5465123653411865  /  PPL :  34.692115783691406 \n",
      "saved\n",
      "/root/anaconda3/envs/bkt/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.\n",
      "  rank_zero_warn(\n",
      "Epoch 0:   0%|                                           | 0/61 [00:00<?, ?it/s]/root/anaconda3/envs/bkt/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:257: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.\n",
      "  warnings.warn(\"To get the last learning rate computed by the scheduler, \"\n",
      "Epoch 0: 100%|‚ñà| 61/61 [00:36<00:00,  1.69it/s, v_num=eehh, train_loss=3.960, lrvalid_loss : 3.5325098037719727  /  PPL :  34.209720611572266 \n",
      "saved\n",
      "Epoch 0: 100%|‚ñà| 61/61 [00:58<00:00,  1.04it/s, v_num=eehh, train_loss=3.960, lrepoch 0 train loss 3.774846315383911\n",
      "Epoch 1: 100%|‚ñà| 61/61 [00:36<00:00,  1.69it/s, v_num=eehh, train_loss=3.730, lrvalid_loss : 3.531691074371338  /  PPL :  34.18172073364258 \n",
      "saved\n",
      "Epoch 1: 100%|‚ñà| 61/61 [00:58<00:00,  1.04it/s, v_num=eehh, train_loss=3.730, lrepoch 1 train loss 3.743920087814331\n",
      "Epoch 2: 100%|‚ñà| 61/61 [00:36<00:00,  1.68it/s, v_num=eehh, train_loss=4.020, lrvalid_loss : 3.5330069065093994  /  PPL :  34.22673034667969 \n",
      "Epoch 2: 100%|‚ñà| 61/61 [00:36<00:00,  1.68it/s, v_num=eehh, train_loss=4.020, lrepoch 2 train loss 3.719383478164673\n",
      "Epoch 3: 100%|‚ñà| 61/61 [00:36<00:00,  1.68it/s, v_num=eehh, train_loss=3.610, lrvalid_loss : 3.5335564613342285  /  PPL :  34.24554443359375 \n",
      "Epoch 3: 100%|‚ñà| 61/61 [00:36<00:00,  1.68it/s, v_num=eehh, train_loss=3.610, lrepoch 3 train loss 3.7044312953948975\n",
      "Epoch 4: 100%|‚ñà| 61/61 [00:36<00:00,  1.67it/s, v_num=eehh, train_loss=3.360, lrvalid_loss : 3.533705949783325  /  PPL :  34.25066375732422 \n",
      "Epoch 4: 100%|‚ñà| 61/61 [00:36<00:00,  1.67it/s, v_num=eehh, train_loss=3.360, lrepoch 4 train loss 3.698671579360962\n",
      "Epoch 4: 100%|‚ñà| 61/61 [00:36<00:00,  1.67it/s, v_num=eehh, train_loss=3.360, lr`Trainer.fit` stopped: `max_epochs=5` reached.\n",
      "Epoch 4: 100%|‚ñà| 61/61 [00:36<00:00,  1.67it/s, v_num=eehh, train_loss=3.360, lr\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Waiting for W&B process to finish... \u001b[32m(success).\u001b[0m\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: / 0.021 MB of 0.021 MB uploaded (0.000 MB deduped)\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Run history:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:                 PPL ‚ñÑ‚ñÅ‚ñÜ‚ñá‚ñà\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:      avg_train_loss ‚ñà‚ñÖ‚ñÉ‚ñÇ‚ñÅ\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:               epoch ‚ñÅ‚ñÅ‚ñÅ‚ñÉ‚ñÉ‚ñÉ‚ñÖ‚ñÖ‚ñÖ‚ñÜ‚ñÜ‚ñÜ‚ñà‚ñà‚ñà‚ñà\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:                grad ‚ñà‚ñÇ‚ñÑ‚ñÅ‚ñÖ‚ñÉ\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:                  lr ‚ñà‚ñá‚ñÖ‚ñÉ‚ñÇ‚ñÅ\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:          train_loss ‚ñÜ‚ñà‚ñÖ‚ñá‚ñÅ‚ñÅ\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: trainer/global_step ‚ñÅ‚ñÅ‚ñÅ‚ñÇ‚ñÉ‚ñÉ‚ñÑ‚ñÖ‚ñÖ‚ñÖ‚ñÜ‚ñÜ‚ñá‚ñà‚ñà‚ñà\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:            val_loss ‚ñÑ‚ñÅ‚ñÜ‚ñá‚ñà\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Run summary:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:                 PPL 34.25066\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:      avg_train_loss 3.69867\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:               epoch 4\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:                grad 992015.75\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:                  lr 0.0\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:          train_loss 3.36455\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: trainer/global_step 299\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:            val_loss 3.53371\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: \n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: üöÄ View run \u001b[33mskt_lr_2e_5_epochs_5_length_512(0fold)\u001b[0m at: \u001b[34m\u001b[4mhttps://wandb.ai/hurontrara/AIxBookathon/runs/lz1zeehh\u001b[0m\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Find logs at: \u001b[35m\u001b[1m./wandb/run-20230117_130545-lz1zeehh/logs\u001b[0m\n"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'additional_training' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 5\u001b[0m\n\u001b[1;32m      2\u001b[0m os\u001b[38;5;241m.\u001b[39menviron[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mCUDA_LAUNCH_BLOCKING\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124m1\u001b[39m\u001b[38;5;124m'\u001b[39m  \n\u001b[1;32m      4\u001b[0m get_ipython()\u001b[38;5;241m.\u001b[39msystem(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mpython3 train_cv.py --name skt_lr_2e_5_epochs_5_length_512  --model_fn model_save  --train_data_name gojun_data  --pretrained_model_name skt/ko-gpt-trinity-1.2B-v0.5  --decoder_lr 2e-5  --batch_size 1  --iteration_per_update 8  --max_length 512  --valid_fold 0  --n_epochs 5  --cosine  --warmup_ratio 0  \u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m----> 5\u001b[0m \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m-\u001b[39m\u001b[43madditional_training\u001b[49m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'additional_training' is not defined"
     ]
    }
   ],
   "source": [
    "import os\n",
    "os.environ['CUDA_LAUNCH_BLOCKING'] = '1'  \n",
    "\n",
    "!python3 train_cv.py --name skt_lr_2e_5_epochs_5_length_512 \\\n",
    "--model_fn model_save \\\n",
    "--train_data_name gojun_data \\\n",
    "--pretrained_model_name skt/ko-gpt-trinity-1.2B-v0.5 \\\n",
    "--decoder_lr 2e-5 \\\n",
    "--batch_size 1 \\\n",
    "--iteration_per_update 8 \\\n",
    "--max_length 512 \\\n",
    "--valid_fold 0 \\\n",
    "--n_epochs 5 \\\n",
    "--cosine \\\n",
    "--warmup_ratio 0 \\\n",
    "\n",
    "--additional_training"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "blNz5kNXk6kF"
   },
   "outputs": [],
   "source": [
    "!pip install sentence_transformers\n",
    "!pip install kss\n",
    "\n",
    "from google.colab import drive\n",
    "drive.mount('/content/drive')\n",
    "%cd '/content/drive/MyDrive/Colab_Notebooks/NLP/Projects/AIxBookathon'\n",
    "\n",
    "!python3 SBERT_sentence.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "id": "KAUa-Q7FoEGn"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: transformers==4.21.2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (4.21.2)\n",
      "Requirement already satisfied: filelock in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (3.9.0)\n",
      "Requirement already satisfied: numpy>=1.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (1.24.1)\n",
      "Requirement already satisfied: packaging>=20.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (23.0)\n",
      "Requirement already satisfied: tokenizers!=0.11.3,<0.13,>=0.11.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (0.12.1)\n",
      "Requirement already satisfied: regex!=2019.12.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (2022.10.31)\n",
      "Requirement already satisfied: tqdm>=4.27 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (4.64.1)\n",
      "Requirement already satisfied: requests in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (2.28.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (6.0)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (0.11.1)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.1.0->transformers==4.21.2) (4.4.0)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->transformers==4.21.2) (1.26.14)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->transformers==4.21.2) (2.1.1)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->transformers==4.21.2) (2022.12.7)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->transformers==4.21.2) (3.4)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: kss in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (4.4.0)\n",
      "Requirement already satisfied: pecab in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from kss) (1.0.8)\n",
      "Requirement already satisfied: networkx in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from kss) (3.0)\n",
      "Requirement already satisfied: emoji==1.2.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from kss) (1.2.0)\n",
      "Requirement already satisfied: regex in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from kss) (2022.10.31)\n",
      "Requirement already satisfied: pyarrow in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pecab->kss) (10.0.1)\n",
      "Requirement already satisfied: pytest in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pecab->kss) (7.2.1)\n",
      "Requirement already satisfied: numpy in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pecab->kss) (1.24.1)\n",
      "Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytest->pecab->kss) (1.1.0)\n",
      "Requirement already satisfied: iniconfig in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytest->pecab->kss) (2.0.0)\n",
      "Requirement already satisfied: pluggy<2.0,>=0.12 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytest->pecab->kss) (1.0.0)\n",
      "Requirement already satisfied: packaging in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytest->pecab->kss) (23.0)\n",
      "Requirement already satisfied: attrs>=19.2.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytest->pecab->kss) (22.2.0)\n",
      "Requirement already satisfied: tomli>=1.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytest->pecab->kss) (2.0.1)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: sentencepiece in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (0.1.97)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: torch_optimizer in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (0.3.0)\n",
      "Requirement already satisfied: torch>=1.5.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch_optimizer) (1.13.1)\n",
      "Requirement already satisfied: pytorch-ranger>=0.1.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch_optimizer) (0.1.1)\n",
      "Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.5.0->torch_optimizer) (8.5.0.96)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.5.0->torch_optimizer) (11.7.99)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.5.0->torch_optimizer) (11.7.99)\n",
      "Requirement already satisfied: typing-extensions in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.5.0->torch_optimizer) (4.4.0)\n",
      "Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.5.0->torch_optimizer) (11.10.3.66)\n",
      "Requirement already satisfied: wheel in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.5.0->torch_optimizer) (0.38.4)\n",
      "Requirement already satisfied: setuptools in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.5.0->torch_optimizer) (65.6.3)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: pytorch-lightning in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (1.8.6)\n",
      "Requirement already satisfied: torchmetrics>=0.7.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (0.11.0)\n",
      "Requirement already satisfied: numpy>=1.17.2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (1.24.1)\n",
      "Requirement already satisfied: tensorboardX>=2.2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (2.5.1)\n",
      "Requirement already satisfied: tqdm>=4.57.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (4.64.1)\n",
      "Requirement already satisfied: torch>=1.9.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (1.13.1)\n",
      "Requirement already satisfied: packaging>=17.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (23.0)\n",
      "Requirement already satisfied: fsspec[http]>2021.06.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (2022.11.0)\n",
      "Requirement already satisfied: typing-extensions>=4.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (4.4.0)\n",
      "Requirement already satisfied: lightning-utilities!=0.4.0,>=0.3.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (0.5.0)\n",
      "Requirement already satisfied: PyYAML>=5.4 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (6.0)\n",
      "Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from fsspec[http]>2021.06.0->pytorch-lightning) (3.8.3)\n",
      "Requirement already satisfied: requests in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from fsspec[http]>2021.06.0->pytorch-lightning) (2.28.1)\n",
      "Requirement already satisfied: protobuf<=3.20.1,>=3.8.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from tensorboardX>=2.2->pytorch-lightning) (3.20.1)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.9.0->pytorch-lightning) (11.7.99)\n",
      "Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.9.0->pytorch-lightning) (8.5.0.96)\n",
      "Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.9.0->pytorch-lightning) (11.10.3.66)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.9.0->pytorch-lightning) (11.7.99)\n",
      "Requirement already satisfied: setuptools in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.9.0->pytorch-lightning) (65.6.3)\n",
      "Requirement already satisfied: wheel in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.9.0->pytorch-lightning) (0.38.4)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (6.0.4)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (4.0.2)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (1.3.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (1.8.2)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (22.2.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (1.3.3)\n",
      "Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (2.1.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->fsspec[http]>2021.06.0->pytorch-lightning) (3.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->fsspec[http]>2021.06.0->pytorch-lightning) (2022.12.7)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->fsspec[http]>2021.06.0->pytorch-lightning) (1.26.14)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: datasets in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (2.8.0)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (6.0)\n",
      "Requirement already satisfied: numpy>=1.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (1.24.1)\n",
      "Requirement already satisfied: pandas in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (1.5.2)\n",
      "Requirement already satisfied: xxhash in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (3.2.0)\n",
      "Requirement already satisfied: dill<0.3.7 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (0.3.6)\n",
      "Requirement already satisfied: pyarrow>=6.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (10.0.1)\n",
      "Requirement already satisfied: tqdm>=4.62.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (4.64.1)\n",
      "Requirement already satisfied: huggingface-hub<1.0.0,>=0.2.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (0.11.1)\n",
      "Requirement already satisfied: requests>=2.19.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (2.28.1)\n",
      "Requirement already satisfied: packaging in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (23.0)\n",
      "Requirement already satisfied: multiprocess in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (0.70.14)\n",
      "Requirement already satisfied: responses<0.19 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (0.18.0)\n",
      "Requirement already satisfied: aiohttp in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (3.8.3)\n",
      "Requirement already satisfied: fsspec[http]>=2021.11.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (2022.11.0)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (1.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (22.2.0)\n",
      "Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (2.1.1)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (1.3.3)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (6.0.4)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (4.0.2)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (1.8.2)\n",
      "Requirement already satisfied: filelock in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from huggingface-hub<1.0.0,>=0.2.0->datasets) (3.9.0)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from huggingface-hub<1.0.0,>=0.2.0->datasets) (4.4.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (2022.12.7)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (1.26.14)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (3.4)\n",
      "Requirement already satisfied: pytz>=2020.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pandas->datasets) (2022.7)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pandas->datasets) (2.8.2)\n",
      "Requirement already satisfied: six>=1.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: evaluate in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (0.4.0)\n",
      "Requirement already satisfied: tqdm>=4.62.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (4.64.1)\n",
      "Requirement already satisfied: fsspec[http]>=2021.05.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (2022.11.0)\n",
      "Requirement already satisfied: datasets>=2.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (2.8.0)\n",
      "Requirement already satisfied: pandas in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (1.5.2)\n",
      "Requirement already satisfied: requests>=2.19.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (2.28.1)\n",
      "Requirement already satisfied: dill in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (0.3.6)\n",
      "Requirement already satisfied: responses<0.19 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (0.18.0)\n",
      "Requirement already satisfied: packaging in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (23.0)\n",
      "Requirement already satisfied: multiprocess in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (0.70.14)\n",
      "Requirement already satisfied: huggingface-hub>=0.7.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (0.11.1)\n",
      "Requirement already satisfied: xxhash in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (3.2.0)\n",
      "Requirement already satisfied: numpy>=1.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (1.24.1)\n",
      "Requirement already satisfied: aiohttp in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (3.8.3)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (6.0)\n",
      "Requirement already satisfied: pyarrow>=6.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (10.0.1)\n",
      "Requirement already satisfied: filelock in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from huggingface-hub>=0.7.0->evaluate) (3.9.0)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from huggingface-hub>=0.7.0->evaluate) (4.4.0)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (1.26.14)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (2022.12.7)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (3.4)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (2.1.1)\n",
      "Requirement already satisfied: pytz>=2020.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pandas->evaluate) (2022.7)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pandas->evaluate) (2.8.2)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.3)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (22.2.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.4)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.2)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.8.2)\n",
      "Requirement already satisfied: six>=1.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas->evaluate) (1.16.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!pip install transformers==4.21.2\n",
    "!pip install kss\n",
    "!pip install sentencepiece\n",
    "!pip install torch_optimizer\n",
    "!pip install pytorch-lightning\n",
    "!pip install datasets\n",
    "!pip install evaluate\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "y3HOkI8OxLGb"
   },
   "outputs": [],
   "source": [
    "!python3 active_prediction.py --fine_tune --name 'skt_lr_2e_5_epochs_5_length_512' --prompt 'ÎÇòÎäî ÎÇ¥ ÎßàÏùåÎåÄÎ°ú Ïì∏ Ïàò ÏûàÎäî ÎèàÏù¥ Ìïú Ïò§ÎßåÏõêÏØ§ ÏÉùÍ∏∞Îäî ÏÉùÌôúÏùÑ ÏÇ¨ÎûëÌïúÎã§.'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "authorship_tag": "ABX9TyNRO9gzx2b4Wix9POiUM09o",
   "machine_shape": "hm",
   "provenance": []
  },
  "gpuClass": "standard",
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
