{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "07127976-90e4-4601-b33a-4375b0ad92ac",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: transformers==4.21.2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (4.21.2)\n",
      "Requirement already satisfied: tokenizers!=0.11.3,<0.13,>=0.11.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (0.12.1)\n",
      "Requirement already satisfied: numpy>=1.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (1.24.1)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (0.11.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (6.0)\n",
      "Requirement already satisfied: tqdm>=4.27 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (4.64.1)\n",
      "Requirement already satisfied: regex!=2019.12.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (2022.10.31)\n",
      "Requirement already satisfied: requests in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (2.28.1)\n",
      "Requirement already satisfied: packaging>=20.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (23.0)\n",
      "Requirement already satisfied: filelock in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from transformers==4.21.2) (3.9.0)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.1.0->transformers==4.21.2) (4.4.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->transformers==4.21.2) (3.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->transformers==4.21.2) (2022.12.7)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->transformers==4.21.2) (2.1.1)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->transformers==4.21.2) (1.26.14)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: sentencepiece in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (0.1.97)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: torch_optimizer in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (0.3.0)\n",
      "Requirement already satisfied: torch>=1.5.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch_optimizer) (1.13.1)\n",
      "Requirement already satisfied: pytorch-ranger>=0.1.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch_optimizer) (0.1.1)\n",
      "Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.5.0->torch_optimizer) (8.5.0.96)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.5.0->torch_optimizer) (11.7.99)\n",
      "Requirement already satisfied: typing-extensions in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.5.0->torch_optimizer) (4.4.0)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.5.0->torch_optimizer) (11.7.99)\n",
      "Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.5.0->torch_optimizer) (11.10.3.66)\n",
      "Requirement already satisfied: setuptools in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.5.0->torch_optimizer) (65.6.3)\n",
      "Requirement already satisfied: wheel in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.5.0->torch_optimizer) (0.38.4)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: pytorch-lightning in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (1.8.6)\n",
      "Requirement already satisfied: numpy>=1.17.2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (1.24.1)\n",
      "Requirement already satisfied: typing-extensions>=4.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (4.4.0)\n",
      "Requirement already satisfied: fsspec[http]>2021.06.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (2022.11.0)\n",
      "Requirement already satisfied: tensorboardX>=2.2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (2.5.1)\n",
      "Requirement already satisfied: tqdm>=4.57.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (4.64.1)\n",
      "Requirement already satisfied: packaging>=17.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (23.0)\n",
      "Requirement already satisfied: lightning-utilities!=0.4.0,>=0.3.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (0.5.0)\n",
      "Requirement already satisfied: torchmetrics>=0.7.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (0.11.0)\n",
      "Requirement already satisfied: PyYAML>=5.4 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (6.0)\n",
      "Requirement already satisfied: torch>=1.9.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pytorch-lightning) (1.13.1)\n",
      "Requirement already satisfied: requests in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from fsspec[http]>2021.06.0->pytorch-lightning) (2.28.1)\n",
      "Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from fsspec[http]>2021.06.0->pytorch-lightning) (3.8.3)\n",
      "Requirement already satisfied: protobuf<=3.20.1,>=3.8.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from tensorboardX>=2.2->pytorch-lightning) (3.20.1)\n",
      "Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.9.0->pytorch-lightning) (8.5.0.96)\n",
      "Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.9.0->pytorch-lightning) (11.7.99)\n",
      "Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.9.0->pytorch-lightning) (11.7.99)\n",
      "Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from torch>=1.9.0->pytorch-lightning) (11.10.3.66)\n",
      "Requirement already satisfied: setuptools in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.9.0->pytorch-lightning) (65.6.3)\n",
      "Requirement already satisfied: wheel in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.9.0->pytorch-lightning) (0.38.4)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (1.8.2)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (22.2.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (1.3.3)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (6.0.4)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (4.0.2)\n",
      "Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (2.1.1)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>2021.06.0->pytorch-lightning) (1.3.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->fsspec[http]>2021.06.0->pytorch-lightning) (3.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->fsspec[http]>2021.06.0->pytorch-lightning) (2022.12.7)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests->fsspec[http]>2021.06.0->pytorch-lightning) (1.26.14)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: datasets in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (2.8.0)\n",
      "Requirement already satisfied: numpy>=1.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (1.24.1)\n",
      "Requirement already satisfied: aiohttp in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (3.8.3)\n",
      "Requirement already satisfied: xxhash in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (3.2.0)\n",
      "Requirement already satisfied: dill<0.3.7 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (0.3.6)\n",
      "Requirement already satisfied: packaging in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (23.0)\n",
      "Requirement already satisfied: pandas in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (1.5.2)\n",
      "Requirement already satisfied: fsspec[http]>=2021.11.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (2022.11.0)\n",
      "Requirement already satisfied: huggingface-hub<1.0.0,>=0.2.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (0.11.1)\n",
      "Requirement already satisfied: tqdm>=4.62.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (4.64.1)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (6.0)\n",
      "Requirement already satisfied: pyarrow>=6.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (10.0.1)\n",
      "Requirement already satisfied: responses<0.19 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (0.18.0)\n",
      "Requirement already satisfied: requests>=2.19.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (2.28.1)\n",
      "Requirement already satisfied: multiprocess in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets) (0.70.14)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (1.3.3)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (1.8.2)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (1.3.1)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (6.0.4)\n",
      "Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (2.1.1)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (22.2.0)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets) (4.0.2)\n",
      "Requirement already satisfied: filelock in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from huggingface-hub<1.0.0,>=0.2.0->datasets) (3.9.0)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from huggingface-hub<1.0.0,>=0.2.0->datasets) (4.4.0)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (1.26.14)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (2022.12.7)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->datasets) (3.4)\n",
      "Requirement already satisfied: pytz>=2020.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pandas->datasets) (2022.7)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pandas->datasets) (2.8.2)\n",
      "Requirement already satisfied: six>=1.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: evaluate in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (0.4.0)\n",
      "Requirement already satisfied: multiprocess in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (0.70.14)\n",
      "Requirement already satisfied: dill in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (0.3.6)\n",
      "Requirement already satisfied: datasets>=2.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (2.8.0)\n",
      "Requirement already satisfied: fsspec[http]>=2021.05.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (2022.11.0)\n",
      "Requirement already satisfied: numpy>=1.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (1.24.1)\n",
      "Requirement already satisfied: responses<0.19 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (0.18.0)\n",
      "Requirement already satisfied: requests>=2.19.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (2.28.1)\n",
      "Requirement already satisfied: tqdm>=4.62.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (4.64.1)\n",
      "Requirement already satisfied: huggingface-hub>=0.7.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (0.11.1)\n",
      "Requirement already satisfied: xxhash in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (3.2.0)\n",
      "Requirement already satisfied: packaging in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (23.0)\n",
      "Requirement already satisfied: pandas in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from evaluate) (1.5.2)\n",
      "Requirement already satisfied: pyarrow>=6.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (10.0.1)\n",
      "Requirement already satisfied: aiohttp in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (3.8.3)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from datasets>=2.0.0->evaluate) (6.0)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from huggingface-hub>=0.7.0->evaluate) (4.4.0)\n",
      "Requirement already satisfied: filelock in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from huggingface-hub>=0.7.0->evaluate) (3.9.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (2022.12.7)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (1.26.14)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (2.1.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests>=2.19.0->evaluate) (3.4)\n",
      "Requirement already satisfied: pytz>=2020.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pandas->evaluate) (2022.7)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from pandas->evaluate) (2.8.2)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.8.2)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.1)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.0.4)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (4.0.2)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.3)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (22.2.0)\n",
      "Requirement already satisfied: six>=1.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas->evaluate) (1.16.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: wandb in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (0.13.8)\n",
      "Requirement already satisfied: setuptools in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (65.6.3)\n",
      "Requirement already satisfied: sentry-sdk>=1.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (1.12.1)\n",
      "Requirement already satisfied: protobuf!=4.21.0,<5,>=3.12.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (3.20.1)\n",
      "Requirement already satisfied: GitPython>=1.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (3.1.30)\n",
      "Requirement already satisfied: pathtools in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (0.1.2)\n",
      "Requirement already satisfied: requests<3,>=2.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (2.28.1)\n",
      "Requirement already satisfied: Click!=8.0.0,>=7.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (8.1.3)\n",
      "Requirement already satisfied: PyYAML in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (6.0)\n",
      "Requirement already satisfied: psutil>=5.0.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (5.9.4)\n",
      "Requirement already satisfied: typing-extensions in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (4.4.0)\n",
      "Requirement already satisfied: docker-pycreds>=0.4.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (0.4.0)\n",
      "Requirement already satisfied: setproctitle in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (1.3.2)\n",
      "Requirement already satisfied: appdirs>=1.4.3 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from wandb) (1.4.4)\n",
      "Requirement already satisfied: six>=1.4.0 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from docker-pycreds>=0.4.0->wandb) (1.16.0)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from GitPython>=1.0.0->wandb) (4.0.10)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests<3,>=2.0.0->wandb) (2.1.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests<3,>=2.0.0->wandb) (3.4)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests<3,>=2.0.0->wandb) (1.26.14)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from requests<3,>=2.0.0->wandb) (2022.12.7)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in /root/anaconda3/envs/bkt/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.0->wandb) (5.0.0)\n",
      "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
      "\u001b[0m"
     ]
    }
   ],
   "source": [
    "!pip install transformers==4.21.2\n",
    "!pip install sentencepiece\n",
    "!pip install torch_optimizer\n",
    "!pip install pytorch-lightning\n",
    "!pip install datasets\n",
    "!pip install evaluate\n",
    "!pip install wandb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "6113af87-a40e-4065-ba99-477083ec8040",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[34m\u001b[1mwandb\u001b[0m: Appending key for api.wandb.ai to your netrc file: /root/.netrc\n"
     ]
    }
   ],
   "source": [
    "# 폴더 옮겨도 돌아가는지 테스팅\n",
    "# 여기 밑에 epochs_4는 wandb에 기록 안돼있던데 제거에 일단 해볼게요\n",
    "# https://wandb.ai/kangrnin/AIxBookathon/runs/bredz35y?workspace=user-kangrnin\n",
    "\n",
    "!wandb login #"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "f17189d9-ee8c-4cec-ab2b-32ba51ef10d6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "os.environ['CUDA_LAUNCH_BLOCKING'] = '1'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cff63dc8-e731-41eb-aa81-8261dde5c520",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "|train| = 17229 |valid| = 1915\n",
      "#total_iters = 10765 #warmup_iters = 0\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Currently logged in as: \u001b[33mhurontrara\u001b[0m. Use \u001b[1m`wandb login --relogin`\u001b[0m to force relogin\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: wandb version 0.13.9 is available!  To upgrade, please run:\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m:  $ pip install wandb --upgrade\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Tracking run with wandb version 0.13.8\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Run data is saved locally in \u001b[35m\u001b[1m./wandb/run-20230115_091241-ziwybvyj\u001b[0m\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Run \u001b[1m`wandb offline`\u001b[0m to turn off syncing.\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: Syncing run \u001b[33mskt_lr_2e_5_epochs_5_length_512(0fold)\u001b[0m\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: ⭐️ View project at \u001b[34m\u001b[4mhttps://wandb.ai/hurontrara/AIxBookathon\u001b[0m\n",
      "\u001b[34m\u001b[1mwandb\u001b[0m: 🚀 View run at \u001b[34m\u001b[4mhttps://wandb.ai/hurontrara/AIxBookathon/runs/ziwybvyj\u001b[0m\n",
      "/root/anaconda3/envs/bkt/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:441: LightningDeprecationWarning: Setting `Trainer(gpus=1)` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=1)` instead.\n",
      "  rank_zero_deprecation(\n",
      "GPU available: True (cuda), used: True\n",
      "TPU available: False, using: 0 TPU cores\n",
      "IPU available: False, using: 0 IPUs\n",
      "HPU available: False, using: 0 HPUs\n",
      "LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]\n",
      "/root/anaconda3/envs/bkt/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py:329: RuntimeWarning: The lr scheduler dict contains the key(s) ['interval'], but the keys will be ignored. You need to call `lr_scheduler.step()` manually in manual optimization.\n",
      "  rank_zero_warn(\n",
      "\n",
      "  | Name  | Type            | Params\n",
      "------------------------------------------\n",
      "0 | model | GPT2LMHeadModel | 1.2 B \n",
      "------------------------------------------\n",
      "629 M     Trainable params\n",
      "533 M     Non-trainable params\n",
      "1.2 B     Total params\n",
      "4,650.225 Total estimated model params size (MB)\n",
      "Sanity Checking: 0it [00:00, ?it/s]/root/anaconda3/envs/bkt/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.\n",
      "  rank_zero_warn(\n",
      "Sanity Checking DataLoader 0: 100%|███████████████| 2/2 [00:01<00:00,  1.85it/s]valid_loss : 4.330705165863037  /  PPL :  75.99785614013672 \n",
      "saved\n",
      "/root/anaconda3/envs/bkt/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.\n",
      "  rank_zero_warn(\n",
      "Epoch 0:   0%|                                        | 0/19144 [00:00<?, ?it/s]/root/anaconda3/envs/bkt/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:257: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.\n",
      "  warnings.warn(\"To get the last learning rate computed by the scheduler, \"\n",
      "Epoch 0:   1%| | 180/19144 [01:39<2:54:19,  1.81it/s, v_num=bvyj, train_loss=3.6"
     ]
    }
   ],
   "source": [
    "!python3 train_cv.py --name skt_lr_2e_5_epochs_5_length_512 \\\n",
    "                     --model_fn model_save \\\n",
    "                     --train_data_name articles_preprocessed_fold \\\n",
    "                     --pretrained_model_name skt/ko-gpt-trinity-1.2B-v0.5 \\\n",
    "                     --decoder_lr 2e-5 \\\n",
    "                     --batch_size 1 \\\n",
    "                     --iteration_per_update 8 \\\n",
    "                     --max_length 512 \\\n",
    "                     --valid_fold 0 \\\n",
    "                     --n_epochs 5 \\\n",
    "                     --cosine \\\n",
    "                     --warmup_ratio 0 "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b8a700a3-83c1-466a-a99d-033f77827d1c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ea0c55d8-aa97-49da-a6c2-582e91189df9",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e817751d-4feb-48c2-bac0-5ed3946edfbb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0d0bc34b-8818-4f7f-8927-a09bc3b028d6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
